language: node_js
node_js:
  - "7.10"
install:
  - npm install -g elm
  - npm install -g elm-doc-test
  - npm install -g elm-test
  - elm-package install -y
  - pushd tests && elm-package install -y && popd
script:
  - elm-doc-test && elm-test
